deployment:
  tasks:
    - export DEPLOYPATH=/home/wideraiu/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp -R index.html $DEPLOYPATH
